language: java
sudo: false
jdk:
- oraclejdk8
install:
- mvn clean package
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
